image: openjdk:8

pipelines:
  default:
    - step:
        name: Default build
        caches:
          - gradle
          - gradlewrapper
        script:
          - bash ./gradlew clean test
          - bash ./gradlew clean build
  pull-requests:
    '**':
      - step:
          name: Build master
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew clean test
            - bash ./gradlew clean build
  branches:
    master:
      - step:
          name: Build master
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew clean test
            - bash ./gradlew clean build
    development:
      - step:
          name: Build development
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew clean test
            - bash ./gradlew clean build
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper